/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageadd;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author djvatio
 */
public class Frmanadeimagen extends javax.swing.JFrame {

    Metodos metodos;
    Boolean encontradoxml = false;
    String nombrejuegoeditado;
    String rutarelativa;
    String nombreimagen;
    /**
     * Creates new form Frmanadeimagen
     */
    public Frmanadeimagen() {
        initComponents();
        metodos = Metodos.getinstancia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brom = new javax.swing.JButton();
        trom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        timagen = new javax.swing.JTextField();
        bimagen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        banadir = new javax.swing.JButton();
        tnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lencontrado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        brom.setText("...");
        brom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bromActionPerformed(evt);
            }
        });

        trom.setEditable(false);

        jLabel1.setText("Ruta rom");

        timagen.setEditable(false);

        bimagen.setText("...");
        bimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimagenActionPerformed(evt);
            }
        });

        jLabel2.setText("Ruta imagen");

        banadir.setText("Añadir imagen");
        banadir.setEnabled(false);
        banadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banadirActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trom, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brom)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(banadir)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timagen, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bimagen))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lencontrado)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brom)
                    .addComponent(trom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bimagen)
                    .addComponent(timagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(lencontrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(banadir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bromActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();

        int returnVal = fc.showOpenDialog(Frmanadeimagen.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            //This is where a real application would open the file.
            
            rutarelativa = metodos.obtenrelativa(fc.getSelectedFile().getAbsolutePath());
            if (rutarelativa != null) {
                System.out.println(rutarelativa);
                nombrejuegoeditado = metodos.cambiacontrabarra(rutarelativa);
                Juego buscajuego = metodos.damejuego(nombrejuegoeditado);
                System.out.println(fc.getSelectedFile().getName());
                if (buscajuego == null) {
                    tnombre.setText(metodos.quitaextension(fc.getSelectedFile().getName()));
                    lencontrado.setText("Juego no encontrado en el XML");
                    encontradoxml = false;
                    banadir.setEnabled(false);
                } else {
                    trom.setText(fc.getSelectedFile().getAbsolutePath());
                    lencontrado.setText("Juego encontrado en el XML");
                    tnombre.setText(buscajuego.getNombre());
                    encontradoxml = true;
                    banadir.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El juego debe estar en una ruta relativa el xml", "Alerta " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_bromActionPerformed

    private void bimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimagenActionPerformed
        // TODO add your handling code here:

        JFileChooser fc = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Imágenes", "png","jpeg","PNG","JPEG","jpg","JPG");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(Frmanadeimagen.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            //This is where a real application would open the file.
            timagen.setText(fc.getSelectedFile().getAbsolutePath());
            nombreimagen = fc.getSelectedFile().getName();
        }
    }//GEN-LAST:event_bimagenActionPerformed

    private void vaciacampos()
    {
        trom.setText("");
        banadir.setEnabled(false);
        tnombre.setText("");
        timagen.setText("");
    }
    
    private void banadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banadirActionPerformed
        // TODO add your handling code here:
        if (trom.getText().length() > 0 && tnombre.getText().length() > 0 && timagen.getText().length() > 0) {

            try {
                metodos.copiaimagen(timagen.getText(), metodos.getpathxml() + "/downloaded_images/" + nombreimagen);
                if (encontradoxml) {
                    metodos.modificajuego(nombrejuegoeditado, tnombre.getText(), "./downloaded_images" + "/" + nombreimagen);
                    vaciacampos();
                } else {
                  //  metodos.anadejuego(nombrejuegoeditado, tnombre.getText(), ".\\downloaded_images" + "\\" + nombreimagen);
                }
            } catch (IOException ex) {
                Logger.getLogger(Frmanadeimagen.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error copiando imagen", "Alerta " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos", "Alerta " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_banadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmanadeimagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmanadeimagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmanadeimagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmanadeimagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmanadeimagen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton banadir;
    private javax.swing.JButton bimagen;
    private javax.swing.JButton brom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lencontrado;
    private javax.swing.JTextField timagen;
    private javax.swing.JTextField tnombre;
    private javax.swing.JTextField trom;
    // End of variables declaration//GEN-END:variables
}
